package Verify;

//TO IMPLEMENT THE LINEAR SEARCH DETERMINE TIME TO SEARCH FOR AN ELEMENT AND REPEAT THE PROCESS FOR DIFFERENT VALUE OF N
// THE NO OF ELEMENT IN LIST TO BE SEARCHED AND PLOT A GRAPH FOR THE TIME TAKEN

public class test {
    public static void main(String[] args) {

    }
}
